version: "3"

services:
  kicking_db:
    image: postgres:13-alpine
    env_file:
      - ../.env
    ports:
      - 5432:5432

  kicking_local:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: poetry run /app/manage.py runserver 0:80
    volumes:
      - ../:/app
    env_file:
      - ../.env
    depends_on:
      - kicking_db
    ports:
      - 8000:80
