version: "3"

services:
  kicking_db:
    image: postgres:13-alpine
    env_file:
      - ../.env

  kicking_prod:
    build:
      context: ../
      dockerfile: ./docker/prod.Dockerfile
    command: poetry run gunicorn -c python:config.gunicorn config.wsgi:application
    env_file:
      - ../.env
    depends_on:
      - kicking_db
    volumes:
      - ../:/app

  kicking_server:
    image: nginx:1.15.8-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../staticfiles/:/staticfiles/
    depends_on:
      - kicking_prod
