version: "3"

services:
  kicking_db:
    image: postgres:13-alpine
    env_file:
      - ../.env.test

  kicking_test:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: poetry run /app/manage.py runserver 0:80
    volumes:
      - ../:/app
    env_file:
      - ../.env.test
    depends_on:
      - kicking_db
