# Generated by Django 3.1.4 on 2020-12-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kicks", "0001_create_kick_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kick",
            options={"ordering": ["-kick_time"]},
        ),
    ]
