# Generated by Django 3.1.5 on 2021-01-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kicks', '0002_order_by_latest_kick_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kick',
            options={'get_latest_by': 'kick_time', 'ordering': ['-kick_time']},
        ),
    ]
