name: Build and push docker image to ECR

on:
  push:
    branches: [master]

jobs:
  build_and_push_docker_image_to_ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/kciter/aws-ecr-action:latest
        with:
          access_key_id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
          repo: wafiq-kicks
          region: ap-southeast-1
          tags: latest,${{ github.sha }}
          dockerfile: docker/prod.Dockerfile
          path: .

  build_react_app_and_upload_to_s3:
    environment: Configure GH Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Start docker container
        run: docker-compose -f docker/docker-compose.test.yml up -d

      - name: Upload static files to S3
        run: AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID }} AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }} AWS_S3_STORAGE_BUCKET_NAME=${{ secrets.AWS_S3_STORAGE_BUCKET_NAME }} AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }} docker container exec docker_kicking_test_1 poetry run python manage.py collectstatic --noinput --settings preggy.config.settings.production
